language: cpp

compiler:
  - clang
  - gcc

os:
- linux
#- osx

branches:
  except:
  - master

branches:
  only:
  - Qtfy

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq graphviz doxygen mscgen

before_script:
- git config --global user.name 'Lukas Woodtli (travis-ci)'
- git config --global user.email woodtli.lukas@gmail.com

script:
# Create doxygen documentation
- bash ./FreeRTOS/run_doxygen.sh

#after_success: